### ISSUE TITLE
Explosion resistance

### ISSUE THREAD

**Issue by ArneADM** [JF-Dunford/Space-Gorilla#12]
**Is your feature request related to a problem? Please describe.**
The problem is the minefield of creepers, we all experience them, they sneak in your house, they hide around the corner and a lot more. But it's frustrating when you constantly have to rebuild or keep filling up those dirt holes. 

**Describe the solution you'd like**
Not sure what the best solution could be but what comes to mind is a plugin for explosion resistance that is active when near chests or maybe work with claims or such? 

**Describe alternatives you've considered**
Thought of different ways to activate the resistance, of course, the option to be always active is there. Most servers work with claimed area maybe even a few blocks more, prevents other people with bad intentions for destroying stuff too (for those who experienced the TNT cannons.
Could work with blocks or chucks.

**Additional context**
I can't really come up with a negative effect of this plugin. People could still take the damage for not paying full attention or not have that corner perfectly lit. 
Looking forward to hearing other opinions. ;-)

**Comment by HippocraticOath** [comment]
This is something I am considering. I don't care for pock-marked landscapes due to creeper explosions, either. Future plugins will likely resolve this, especially with land claiming. However choosing a proper starting location is already imperative for multiple aspects in the game. Having a place that is easily defensible and limits spawns to prevent creepers from smearing you and your structures across the terrain does add to the need to protect your things.

We'll likely revisit this issue in beta. The big question is are we taking away too much risk by limiting creeper explosions (which you can stop by using shears on creepers!) or does the presence of creeper explosions cause too much tedium or grief for the player?

Closed for now since I would like to continue your experiences and see if they end up impacts your gameplay negatively.
